### ISSUE TITLE
mincss crashes when stylesheet links have query strings

### ISSUE THREAD

**Issue by layoutanalysis** [peterbe/mincss#53]
```
>mincss http://web.archive.org/web/20140208025552/http://www.clarin.com/
[output omitted]
FOR /static/css/banner-styles.css?v=1516052760.0
Traceback (most recent call last):
  File "c:\program files\anaconda3\lib\runpy.py", line 184, in _run_module_as_ma
in
    "__main__", mod_spec)
  File "c:\program files\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Anaconda3\Scripts\mincss.exe\__main__.py", line 9, in <
module>
  File "c:\program files\anaconda3\lib\site-packages\mincss\main.py", line 69, i
n main
    return run(args) or 0
  File "c:\program files\anaconda3\lib\site-packages\mincss\main.py", line 37, i
n run
    with io.open(os.path.join(output_dir, orig_name), 'w') as f:
OSError: [Errno 22] Invalid argument: './output\\banner-styles.css?v=1516052760.
0'
```

**Comment by peterbe** [comment]
Interesting. But it's unlikely that I'll get around to making a patch to fix this. Do you want to attempt to write a PR?
